---
spring:

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    org.springframework.web: INFO
    za.co.reegz: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
